### PR TITLE
Always close the cluster on exception

### PR DESCRIPTION
**Pull request by philip-doctor**
When a Cluster instance is instantiated, there are a number of underlying threads and resources created by the DataStax Java driver.  These resources *must* be cleaned up or they will lead to a resource leak.

For example, let's say we are attempting to connect to a Cassandra cluster with PasswordAuthenticator but we forget to specify a username, password in our attempt.  The result is an Exception, however if we continue to retry this operation, we end up with OOM errors.

Here's a tiny gist that you can try yourself, it will recreate the exception https://gist.github.com/philip-doctor/26910ca747c33e279203

Here's the end result with visualvm http://imgur.com/vuxezym&WQrFDR7#0
You can see over 2k threads were created.

To fix this, we *must* call .close() on the Cluster that was instantiated, however if there is an exception generated by .connect, the caller will fail to get a Session back and have no way to call .close on Cluster.

I picked what I thought was the simplest possible fix that did not impact your existing API.

VisualVM on fix:
http://imgur.com/vuxezym&WQrFDR7#1

### CODE REVIEW

**Comment by philip-doctor** [comment]
Ahhh.. I see there's a CI failure, I'm sorry I'm not familiar with your system, is it possible to get the log output on the failure?  My unit tests seem to be passing locally.

**Comment by michaelklishin** [comment]
CI failures is a Travis problem: for some reason Cassandra sometimes doesn't start in a reasonable amount of time.

**Comment by ifesdjeen** [comment]
:+1: great job @philip-doctor, very well described issue, too!

**Comment by arr-ee** [comment]
Is there a chance to get this released any time soon? We kinda need this fix.

**Comment by michaelklishin** [comment]
@arr-ee later today.

**Comment by arr-ee** [comment]
@michaelklishin awesome, thx!

**Comment by michaelklishin** [comment]
`2.1.0-beta1` and `2.0.1` were released last night.

**Pull request merged**
