### PR TITLE
Remove unused specs and pieces of code

### PR DESCRIPTION
**Pull request by killthekitten**

### CODE REVIEW

**Comment by michaelklishin** [comment]
What makes you believe the tests are "unused"?

**Comment by killthekitten** [comment]
@michaelklishin I had strong doubts about it, of course :)

I'm making an attempt to fix specs in master branch, but in fact I shouldn't have sent PR this early

**Comment by ifesdjeen** [comment]
@killthekitten the thing is API has changed, so the new way to do same thing is via execute:

```cql
(client/execute session
                (client/build-statement "SELECT * FROM users")
                :retry-policy (:downgrading-consistency policies/retry-policies)
                :consistency-level (:any policies/consistency-levels))
```

I'd leave the `with-consistency-level` test, just port them to the new API. 

What was wrong with `test-select-where-without-fetch`?

**Comment by killthekitten** [comment]
@ifesdjeen in previous commit I've just misunderstood the real purpose of `test-select-where-without-fetch` being on it's place.

Does the fix looks ok now? I've also removed `with-consistency-level` macro, since I didn't find any other usages in the code. 

And thank you for your help.

**Comment by ifesdjeen** [comment]
Ok, much better now :)

**Pull request merged**
