### PR TITLE
Corrected mispelling of :pedantic? in project.clj

### PR DESCRIPTION
**Pull request by Rovanion**
I simply noticed that you had misspelt a key in your project.clj, so I corrected it.

### CODE REVIEW

**Comment by michaelklishin** [comment]
I don't think it's a typo, not according to [lein-pedantic](https://github.com/xeqi/lein-pedantic)'s README. That project is now deprecated but that's a separate discussion.

**Comment by Rovanion** [comment]
It's been deprecated by the features now included in Leiningen I'd assume, where one of these is triggered by the :pedantic?, the docs for the key reads:

>  ;; What to do in the case of version issues. Defaults to :ranges, which
>  ;; warns when version ranges are present anywhere in the dependency tree,
>  ;; but can be set to true to warn for both ranges and overrides, or :abort
>  ;; to exit in the case of ranges or overrides.

If this is what you want, then I think the patch still applies.

**Comment by michaelklishin** [comment]
Consider linking to the document you are quoting.

**Comment by Rovanion** [comment]
Leiningen seems to be lacking in the documentation department, but I was quoting the sample project file they've got:

https://github.com/technomancy/leiningen/blob/master/sample.project.clj#L77

**Comment by michaelklishin** [comment]
Yes, I found it using GitHub search (and the comments suggested it was that file), thanks.

**Comment by Rovanion** [comment]
Cheers!

**Pull request merged**
